# Generated by Django 4.2.7 on 2025-10-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('bank_type', models.CharField(default='unknown', max_length=50)),
                ('account_type', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('shopping', 'Shopping'), ('transport', 'Transportation'), ('entertainment', 'Entertainment'), ('bills', 'Bills & Utilities'), ('income', 'Income'), ('transfer', 'Transfers'), ('healthcare', 'Healthcare'), ('business', 'Business Expenses'), ('other', 'Other')], default='other', max_length=20)),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.5, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='extraction_app.pdfdocument')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['date'], name='extraction__date_ec12d9_idx'), models.Index(fields=['category'], name='extraction__categor_fda8e4_idx'), models.Index(fields=['transaction_type'], name='extraction__transac_2899af_idx')],
            },
        ),
    ]
